[build-system]
build-backend = "maturin"
requires = [ "maturin>=1,<2" ]

[project]
name = "drf-accelerator"
version = "0.1.1"
description = "A high-performance Rust-backed accelerator for Django REST Framework."
readme = { file = "README.md", content-type = "text/markdown" }
keywords = [ "djangorestframework", "drf", "performance", "serialization" ]

license = { text = "MIT" }
maintainers = [
  { name = "Pravin" },
]
authors = [
  { name = "Pravin" },
]

requires-python = ">=3.10,<3.14"

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: Django",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Rust",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
  "djangorestframework>=3.12",
]

urls."Home Page" = "https://github.com/p-r-a-v-i-n/drf-accelerator"
urls.Issues = "https://github.com/p-r-a-v-i-n/drf-accelerator/issues"
urls.Repository = "https://github.com/p-r-a-v-i-n/drf-accelerator"

[dependency-groups]
dev = [
  "pre-commit",
  "ruff",
]

test = [
  "pytest",
  "pytest-benchmark",
  "pytest-codspeed",
]

[tool.maturin]
python-source = "drf_accelerator"
manifest-path = "drf_accelerator/Cargo.toml"
module-name = "drf_accelerator.drf_accelerator"

[tool.ruff]
target-version = "py310"
line-length = 88
exclude = [ "examples" ]

lint.select = [ "E", "F", "I", "UP", "W" ]
lint.isort.known-first-party = [ "drf_accelerator" ]
